addons:
  apt:
    packages:
      - git
      - make
      - curl

install:
  - make init

env:
  - TERRAFORM_VERSION=0.12.25
  - TERRAFORM_VERSION=0.12.24

script:
  - make terraform/install
  - make terraform/get-plugins
  - make terraform/get-modules
  - make terraform/lint
  - make terraform/validate